togglz:
  console:
    path: /togglz
    secured: false
    use-management-port: false
  features:
    MESSAGE:
      enabled: true
    DESCRIPTION:
      enabled: true

spring:
  datasource:
    username: sa
    password: password
